name: ESLint

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm
      run: npm install
    - name: eslint
      uses: gimenete/eslint-action@1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        job-name: eslint
